### PR TITLE
Gitcoin: Donder's stylesheet

### PR DESCRIPTION
**Pull request by Elaniobro**
#### Description:
* Moved file structure around
* Updated `theme-override` stylesheet
* Added multiple background properties for last slide
* Added unique background for first slide
* Added `.editorconfig`
* [Test url](https://gitpitch.com/elaniobro/ForkPPM/master#/6)
#### Issue(s):
* #1

### CODE REVIEW

**Comment by Elaniobro** [comment]
@TimVanMourik Please take a look, I followed the instructions best I could. I think the last slide, the `Brainzzz.png` image is too dark and could probably use some direction in how to handle.

`MAKE THE ENTIRE LAYOUT A PLEASING PRESENTATION TEMPLATE` is pretty arbitrary, if you could provide a bit more instruction/guidance, I can knock this out quickly.

**Comment by TimVanMourik** [comment]
Thanks, great! Couple of remarks:
* The FirstSlide picture is indeed the first slide now. Most slides seem to be have an overlapping first slide and standard slide though (see screenshot, lower left) but not all (upper right). Do you think it could be set to be exclusively the first slide?
* The LastSlide.png is now the last slide for the presentation _horizontally_ but also _vertically_ (screenshot, lower right). Only to the horizontal last slide needs to be different, as I generally use it as a "Thank you" slide.
* I purposefully made the statement a bit vague as it's open for interpretation, but I'm happy with something as simple as "a slide that adheres to the 6 by 6 rule (i.e. max six bullet points per slide, each with a max of six words) should fit, and bullet points should indeed look somewhat structured". But more generally, the closer it is to the example mentioned in the issue, the better.
* As there's not supposed to be text in the last slide except 'thank you' and /or some website URL, the darkness of the brains picture is not really an issue to me. But if you've got suggestions to improve it, knock yourself out :)

screenshot

**Comment by Elaniobro** [comment]
@TimVanMourik Have a look, its take me a few commits to get it. First time working with `gitpitch` (cool presentation thing btw) 

* Overlapping slides of `Background.png` & `FirstSlide.png` is fixed.
* Last slide in the horizontal slide showing the `Brainzzz.png` image is fixed
* I believe this adheres to the `6x6` rule
* Not sure what to do, I did want to reduce the `opacity` of the background image, but since there are two, you can not affect one with out the other, i.e. logo, becoming affected. I left it as is. 

Please re-review and provide any feedback.

**Comment by TimVanMourik** [comment]
Great work! I'm happy as it is. With regard to the things you're not sure about: I specifically made an issue ( #3 ) for integrating content and stylesheet, so let's leave that for later.

**Pull request merged**
